#server:
#  port: 8888
#  # 下面是配置undertow作为服务器的参数
#  undertow:
#    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
#    io-threads: 4
#    # 工作任务线程池，默认为io-threads的8倍
#    worker-threads: 32

#生成自签名证书命令
#  keytool -genkeypair -alias selfsigned_localhost_sslserver -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore mqxu-ssl-key.p12 -validity 3650
server:
  port: 8888
  httpPort: 80
  ssl:
    key-store: mqxu-ssl-key.p12
    key-store-password: 123456
    key-store-type: PKCS12