server:
  port: 9090

logging:
  config: classpath:log4j2-prod.xml

#logging:
#  level:
#    root: info
#  file:
#    name: /Users/apple/Documents/logs/my.log
#  logback:
#    rollingpolicy:
#      max-file-size: 1MB
#      max-history: 7
#  pattern:
#    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger : %msg%n'